name: deploy-frontend-to-stage
on: 
  push:
    branches: 
      - main
    paths:
      - 'package.json'
jobs: 
  deploy-to-stage: 
    runs-on: ubuntu-latest
    steps: 
      - name: any-step
        run: echo "Hello world"
